// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdyorvkiqsiaamhrgjeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkeW9ydmtpcXNpYWFtaHJnamVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5ODQwMDcsImV4cCI6MjA2MDU2MDAwN30.0LMn_62OPYkdZhCIfisQdDrva4GfHLKN32Lq91dyC6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);